python3: can't open file '/mnt/anom_proj/logs/convauto.py': [Errno 2] No such file or directory
